const router = require('express').Router()
const UserController = require('../controllers/user-controller.js')
const ProductController = require('../controllers/product-controller.js')
const authentication = require('../middlewares/authentication.js')
router.post('/login',UserController.postLogin)
router.post('/register',UserController.postRegister)
router.use(authentication)
router.post('/',ProductController.postProduct)
// router.put('/:id',ProductController.putProduct)
// router.delete('/:id',ProductController.deleteProduct)
module.exports = router
